
global_config:
  verbose: true

agent_type: "modular_agent"

agent:
  # 组件配置
  components:

    action:
      name: "android_action"
      params: {}

    # --- 感知器 ---
    perception:
      name: "grid_perception"
      params: {}
        
    # --- 大脑 ---
    reasoning:
      name: "universal_reasoning"
      params:
        preset: "general_vlm_type"
      llm:
        name: "openai_llm"
        params:
          api_key: "sk-xxx"
          base_url: "https://api.openai.com/v1"
          model: "gpt-4o"
    
    # --- 记忆 ---
    memory:
      name: "sliding_window_memory"
      params: { window_size: 6 }

    # --- 规划器 ---
    planner:
      name: "universal_planner" 
      params:
        preset: "manager_style"
      llm:
        name: "openai_llm"
        params:
          api_key: "sk-xxx"
          base_url: "https://api.openai.com/v1"
          model: "gpt-4o"
