
global_config:
  verbose: true

agent_type: "modular_agent"

agent:

  # 组件配置
  components:

    action:
      name: "harmony_action"
      params: {}

    # --- 感知器 ---
    perception:
      name: "omniparser_perception"
      params:
        url: "omniparser-url"
        
    # --- 大脑 ---
    reasoning:
      name: "universal_reasoning"
      
      params:
        preset: "general_vlm_type"
      llm:
        name: "openai_llm"
        params:
          api_key: "your-api-key"
          base_url: "your-base-url"
          model: "gpt-4o"
          temperature: 0.1
          max_tokens: 2048
    
    # --- 记忆 ---
    memory:
      name: "summary_memory"
      llm:
        name: "openai_llm"
        params:
          api_key: "your-api-key"
          base_url: "your-base-url"     
          model: "gpt-4o"

    # --- 规划器 ---
    planner:
      name: "universal_planner" 
      
      params:
        preset: "mobimind_style"

      llm:
        name: "openai_llm"
        params:
          api_key: "your-api-key"
          base_url: "your-base-url"
          model: "qwen3-4b"